FROM jupyter/base-notebook

WORKDIR /home/jovyan/work/
USER root
RUN apt-get update
RUN apt-get install -y libglib2.0-0 libsm6 libxrender-dev libxext6 ffmpeg
USER jovyan

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
